name: immenCity
main: net.weasel.immenCity.immenCity
version: 1.0
commands:
  icity:
    description: "Save and load entire chunks of your world"
    usage: "(handled by plugin)"
    aliases: immencity
  istart:
    description: "Save and load entire chunks of your world"
    usage: "(handled by plugin)"
  iload:
    description: "Save and load entire chunks of your world"
    usage: "(handled by plugin)"
  isave:
    description: "Save and load entire chunks of your world"
    usage: "(handled by plugin)"
  ilist:
    description: "Save and load entire chunks of your world"
    usage: "(handled by plugin)"
  imeasure:
    description: "Measure the dimensions of a structure"
    usage: "(handled by plugin)"
    aliases: measure