name: Chunker
main: net.weasel.immenCity.immenCity
version: 1.0
commands:
  chunker:
    description: "Save and load entire chunks of your world"
    usage: "(handled by plugin)"
  cstart:
    description: "Shortcut to set the start point for chunk save/load operations."
    usage: "(handled by plugin)"
